metabase:
  build: ./metabase 
  ports:
    - 3000:3000
  links:
    - mysql
mysql:
  build: ./mysql
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=$DB_PW
    - MYSQL_DATABASE=dht11
  command: bash -c "mysql -uroot -p$DB_PW dht11 < create_table.sql"
